# this is redis config file
[list]
    [list.default]
        proxy_list = ["192.168.220.151:31079"]
        password = "gem816"
        max_active = 100
        max_idle = 100
        down_grade = false